[build]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "llvm-args=-unroll-threshold=400",
    "-C", "llvm-args=-fp-contract=fast",
    "-Z", "unstable-options",
    "-C", "panic=immediate-abort"
]

[unstable]
build-std = ["std", "panic_abort"]
